export { default as BorrowerInfo } from './BorrowerInfo'
export { default as LoanDetails } from './LoanDetails'
export { default as ScheduleInfo } from './ScheduleInfo'
export { default as ProductDetails } from './ProductDetails'
export { default as NotesSection } from './NotesSection'
export { default as NotificationSection } from './NotificationSection'
export { default as HistoryModal } from './HistoryModal'

// New extracted components
export { default as LoadingState } from './LoadingState'
export { default as ErrorState } from './ErrorState'
export { default as NotFoundState } from './NotFoundState'
export { default as HeaderSection } from './HeaderSection'
export { default as BorrowerInfoCard } from './BorrowerInfoCard'
export { default as LoanDetailsCard } from './LoanDetailsCard'
export { default as ScheduleInfoCard } from './ScheduleInfoCard'
export { default as ProductDetailsCard } from './ProductDetailsCard'
export { default as NotesCard } from './NotesCard'
export { default as NotificationCard } from './NotificationCard'
export { default as ReminderStatusCard } from './ReminderStatusCard'